### ISSUE TITLE
Access denied when editing or deleting tampers

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/feeds_tamper#4] opened 2020-07-16 05:51 UTC
When trying to edit or delete a tamper, I get an 'Access denied' error:

> You are not authorized to access this page.

**Comment by ghost** [comment] 2020-07-16 06:14
It looks like the issue is here (in `feeds_tamper_access()`):

```php
elseif (is_object($importer)) {
  $importer = $importer->id;
}
```

All keys in the `$importer` object are suffixed with `:protected`, so the code above should instead be:

```php
elseif (is_object($importer)) {
  $importer = $importer->id:protected;
}
```

(or whatever's adding that `:protected` suffix should be removed).

**Comment by ghost** [comment] 2020-07-16 06:18
Actually, even if I hack the module to return TRUE regardless, I then get this error:

> Empty configuration identifier.

So possibly a larger issue here...

**Comment by herbdool** [comment] 2020-07-17 15:14
Maybe it's a PHP version issue. Perhaps we need to ensure it's forward compatible. I've been testing it in Lando and default is PHP 7.2

**Comment by herbdool** [comment] 2020-07-17 15:59
I think this is the easiest approach: https://github.com/backdrop-contrib/feeds_tamper/commit/e60b478e08a4ab5914d92604096da0d4c03f6250 - access it with the getter which is available in the parent class.

**Comment by herbdool** [comment] 2020-07-18 19:49
I'm going to say this is tentatively solved. Let me know if not.

**Comment by ghost** [comment] 2020-07-21 23:27
Sorry, didn't fix it. I still get:

> Access denied
You are not authorized to access this page.

**Comment by herbdool** [comment] 2020-09-18 19:38
Is this still an issue @BWPanda. I haven't been able to replicate.

**Comment by ghost** [comment] 2020-09-18 20:38
@herbdool Sorry, I had to stop using this module.

**Comment by laryn** [comment] 2024-01-19 17:03
Closing since we can't replicate. If someone has this issue again, please reopen or open a new issue with steps to reproduce.

**Closed as completed by laryn** 2024-01-19 17:03 UTC
